dist: focal
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
services:
  - redis-server
addons:
  postgresql: 13
env:
  global:
    - STORAGE_REDIS_DB_INDEX=1
    - SESSION_REDIS_DB_INDEX=1
    - GIVE_SESSION_KEY=99999
    # These variables are intentionally blank in order establish the connection to the Postgresql server:
    - DB_ENV_POSTGRESQL_USER_TEST=
    - DB_ENV_POSTGRESQL_USER=
    - DB_ENV_POSTGRESQL_PASS_TEST=
    - DB_ENV_POSTGRESQL_PASS=
    - DB_PORT_5432_TCP_ADDR_TEST=
    - DB_PORT_5432_TCP_ADDR=
before_install:
  - gem install bundler -v 2.2.28
  - yarn --ignore-engines
before_script:
  - bundle exec rails db:setup RAILS_ENV=test
script:
  - bundle exec rails test
  - bundle exec standardrb
  - bundle exec bundle audit check --update
  - bundle exec brakeman --ensure-latest -A -q --no-pager
  - yarn run improved-yarn-audit --ignore-dev-deps
