name: Ruby

on:
  pull_request:
    branches: [master]
  push:
    branches: [staging]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Bundle audit
        run: bundle exec bundle audit check --update --ignore CVE-2015-9284

      - name: Brakeman
        run: bundle exec brakeman -A -q --ensure-latest --no-pager

      - name: StandardRB
        run: bundle exec standardrb --format simple

      - name: Install yarn dependencies
        run: yarn --ignore-engines

      - name: Yarn audit
        run: yarn run improved-yarn-audit --ignore-dev-deps
